server:
  port: 9999

spring:
  profiles:
    active: default
  cloud:
#    config:
#      uri: http://localhost:9000
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test-route-yml
          uri: http://httpbin.org:80
          predicates:
          - Path=/get/**
gs-route-java-demo-httpbin:
  ribbon:
    eureka:
      enabled: true
    eager-load:
      enabled: true
    ServerListRefreshInterval: 15000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
