server:
  port: 19999

spring:
  profiles:
    active: default
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#gs-route-java-demo-httpbin:
#  ribbon:
#    eureka:
#      enabled: false
#    eager-load:
#      enabled: false
#    ServerListRefreshInterval: 15000
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: false
#    fetch-registry: false
management.endpoint.gateway.enabled: true # default value
management.endpoints.web.exposure.include: gateway